apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octez-smart-rollup-node.fullname" . }}
  labels:
    {{- include "octez-smart-rollup-node.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | nindent 4 }}
