apiVersion: v1
kind: Service
metadata:
  name: {{ include "octez-smart-rollup-node.fullname" . }}
  labels:
    {{- include "octez-smart-rollup-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "octez-smart-rollup-node.selectorLabels" . | nindent 4 }}
