apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "octez-smart-rollup-node.fullname" . }}
  labels:
    {{- include "octez-smart-rollup-node.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "octez-smart-rollup-node.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "octez-smart-rollup-node.fullname" . }}-headless
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "octez-smart-rollup-node.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "octez-smart-rollup-node.serviceAccountName" . }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
      {{- if .Values.initContainers }}
        {{- tpl (toYaml .Values.initContainers | nindent 8) $ }}
      {{- end }}
      {{- if .Values.initDownloadSnapshot.enabled }}
      - name: init-download-snapshot
        image: "{{ .Values.initDownloadSnapshot.image.repository }}:{{ .Values.initDownloadSnapshot.image.tag }}"
        imagePullPolicy: {{ .Values.initDownloadSnapshot.image.pullPolicy }}
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          {{- include "octez-smart-rollup-node.defaultSnapshotDownloadCommand" . | nindent 10 }}
        resources:
      {{ toYaml .Values.initDownloadSnapshot.resources | nindent 12 }}
        volumeMounts:
          - name: storage
            mountPath: "/data"
      {{- end }}
      {{- if .Values.initChownData.enabled }}
      - name: init-chown-data
        image: "{{ .Values.initChownData.image.repository }}:{{ .Values.initChownData.image.tag }}"
        imagePullPolicy: {{ .Values.initChownData.image.pullPolicy }}
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/data"]
        resources:
      {{ toYaml .Values.initChownData.resources | nindent 12 }}
        volumeMounts:
          - name: storage
            mountPath: "/data"
      {{- end }}
      {{- if .Values.initImportSnapshot.enabled }}
      - name: init-import-snapshot
        image: "{{ .Values.initImportSnapshot.image.repository }}:{{ .Values.initImportSnapshot.image.tag }}"
        imagePullPolicy: {{ .Values.initDownloadSnapshot.image.pullPolicy }}
        command:
          {{- include "octez-smart-rollup-node.defaultSnapshotImportCommand" . | nindent 10 }}
        resources:
          {{ toYaml .Values.initImportSnapshot.resources | nindent 12 }}
        volumeMounts:
           - name: storage
             mountPath: "/data"
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- include "octez-smart-rollup-node.defaultCommand" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
              {{ toYaml .Values.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: storage
              mountPath: "/data"
            - name: config
              mountPath: "/config"
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- range $key, $value := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "octez-smart-rollup-node.fullname" $ }}-env
                  key: {{ $key }}
          {{- end }}
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
      {{- if .Values.extraContainers }}
        {{ tpl (toYaml .Values.extraContainers | nindent 8) $ }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
        - name: config
          configMap:
            name: {{ include "octez-smart-rollup-node.fullname" . }}
  {{- if not .Values.persistence.enabled }}
        - name: storage
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        {{- toYaml .Values.persistence.annotations | nindent 8 }}
    spec:
      accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- if .Values.persistence.selector }}
      selector:
        {{- toYaml .Values.persistence.selector | nindent 8 }}
      {{- end }}
  {{- end }}
