# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

# -- Number of replicas
replicas: 1

image:
  # -- geth container image repository
  repository: tezos/tezos
  # -- geth container image tag
  tag: octez-v21.4
  # -- geth container pull policy
  pullPolicy: IfNotPresent

# -- Extra args for the geth container
extraArgs: []
#- --enable-performance-metrics

config: |
  {
    "smart-rollup-address": "sr1Ghq66tYK9y3r8CC1Tf8i8m5nxh8nTvZEf",
    "smart-rollup-node-operator": {},
    "rpc-addr": "0.0.0.0",
    "fee-parameters": {},
    "pre-images-endpoint": "https://snapshots.eu.tzinit.org/etherlink-mainnet/wasm_2_0_0",
    "mode": "observer",
    "history-mode": "full"
  }

# Endpoint for L1 octez node
octezEndpoint: https://rpc.tzkt.io/mainnet

# -- Template used for the default command
# @default -- See `values.yaml`
defaultCommandTemplate: |
  - sh
  - -c
  - >
    cp /config/config.json /data;

    octez-smart-rollup-node
    --endpoint {{ .Values.octezEndpoint }}
    run
    --data-dir /data
    --acl-override allow-all
    --metrics-addr 0.0.0.0:9933
  {{- range .Values.extraArgs }}
    {{ tpl . $ }}
  {{- end }}

# -- Legacy way of overwriting the default command. You may prefer to change defaultCommandTemplate instead.
customCommand: []


ingress:
  # -- Ingress resource for the HTTP API
  enabled: false
  # -- Annotations for Ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # -- Ingress host
  hosts:
    - host: chart-example.local
      paths: []
  # -- Ingress TLS
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Affinity configuration for pods
affinity: {}

# -- Image pull secrets for Docker images
imagePullSecrets: []

# -- Annotations for the StatefulSet
annotations: {}

# -- Startup probe
# @default -- See `values.yaml`
startupProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 120
  periodSeconds: 10

# -- Liveness probe
# @default -- See `values.yaml`
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 120

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

# -- HTTP Port
httpPort: 8932

# -- Metrics Port
metricsPort: 9933

# -- Node selector for pods
nodeSelector: {}

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: false
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
    - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 200Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: null
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

# -- Pod labels
podLabels: {}

# -- Pod annotations
podAnnotations: {}

# -- Pod management policy
podManagementPolicy: OrderedReady

# -- Pod priority class
priorityClassName: null

rbac:
  # -- Specifies whether RBAC resources are to be created
  create: false
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  clusterRules:
    # Required to obtain the nodes external IP
    - apiGroups: [""]
      resources:
        - "nodes"
      verbs:
        - "get"
        - "list"
        - "watch"
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  rules:
    # Required to get information about the serices nodePort.
    - apiGroups: [""]
      resources:
        - "services"
      verbs:
        - "get"
        - "list"
        - "watch"

# -- Resource requests and limits
resources: {}
# limits:
#   cpu: 500m
#   memory: 2Gi
# requests:
#   cpu: 300m
#   memory: 1Gi

# -- The security context for pods
# @default -- See `values.yaml`
securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

# -- The security context for containers
# @default -- See `values.yaml`
containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- How long to wait until the pod is forcefully terminated
terminationGracePeriodSeconds: 60

# -- Tolerations for pods
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Topology Spread Constraints for pods
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
topologySpreadConstraints: []

# -- Define the PodDisruptionBudget spec
# If not set then a PodDisruptionBudget will not be created
podDisruptionBudget: {}
# minAvailable: 1
# maxUnavailable: 1

# -- Update stategy for the Statefulset
updateStrategy:
  # -- Update stategy type
  type: RollingUpdate

# -- Additional init containers
initContainers: []
# - name: my-init-container
#   image: busybox:latest
#   command: ['sh', '-c', 'echo hello']

# -- Additional containers
extraContainers: []

# -- Additional volumes
extraVolumes: []

# -- Additional volume mounts
extraVolumeMounts: []

# -- Additional ports. Useful when using extraContainers or extraContainerPorts
extraPorts: []

# -- Additional ports for the main container
extraContainerPorts: []

# -- Additional env variables
extraEnv: []

# -- Additional env variables injected via a created secret
secretEnv: {}
# MY_PASSWORD: supersecret

initChownData:
  # -- Init container to set the correct permissions to access data directories
  enabled: true
  image:
    # -- Container repository
    repository: busybox
    # -- Container tag
    tag: "1.34.0"
    # -- Container pull policy
    pullPolicy: IfNotPresent
  # -- Resource requests and limits
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

initDownloadSnapshot:
  # -- Init container to download rollup snapshot
  enabled: true
  image:
    repository: curlimages/curl
    tag: "8.11.0"
    pullPolicy: IfNotPresent

  url: "https://snapshots.eu.tzinit.org/etherlink-mainnet/eth-mainnet.full"

  snapshotDownloadCmdTemplate: |
    - sh
    - -c
    - >
     echo "Downloading snapshot from {{ .Values.initDownloadSnapshot.url }}";
     curl -LfsS {{ .Values.initDownloadSnapshot.url }} -o /data/rollup.snapshot

  # -- Resource requests and limits
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

initImportSnapshot:
  # -- Init container to import snapshot rollup
  enabled: true

  image:
    repository: tezos/tezos
    tag: octez-v21.4
    pullPolicy: IfNotPresent

  snapshotImportCmdTemplate: |
    - sh
    - -c
    - >
      echo "Importing snapshot from {{ .Values.initDownloadSnapshot.url }}";
      octez-smart-rollup-node -E {{ .Values.octezEndpoint }} snapshot import /data/rollup.snapshot --data-dir /data --no-check;
      rm -vf /data/rollup.snapshot

  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: false
  # -- Path to scrape
  path: /metrics
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []
